### ISSUE TITLE
Nothing is working.

### ISSUE THREAD

**Issue by mercuryyy** [cloudconvert/n8n-nodes-cloudconvert#1]
Keep getting errors when trying to use the n8n node

Can you please provide a working example or perhaps some live templates we can copy settings from. 

The only thing that worked was fetching a website image from a URL

when trying all other options using the binary option nothing works.

"No file name given for input file." or Other errors when playing with deferent "JSON" formats for the additional settings.

**Comment by hagaluly** [comment]
same here. node is not working
